# Generated by Django 4.0.3 on 2022-06-12 10:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=320, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=18, null=True)),
            ],
            options={
                'db_table': 'creators',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Interviewee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=320)),
                ('first_name', models.CharField(blank=True, max_length=63, null=True)),
                ('last_name', models.CharField(blank=True, max_length=63, null=True)),
            ],
            options={
                'db_table': 'interviewees',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField(blank=True, null=True)),
                ('required', models.BooleanField()),
            ],
            options={
                'db_table': 'items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.item')),
            ],
            options={
                'db_table': 'options',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paused', models.BooleanField()),
                ('anonymous', models.BooleanField()),
                ('greeting', models.TextField(blank=True, null=True)),
                ('farewell', models.TextField(blank=True, null=True)),
                ('creator_id', models.ForeignKey(db_column='creator_id', on_delete=django.db.models.deletion.CASCADE, to='api.creator')),
            ],
            options={
                'db_table': 'surveys',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SurveySent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interviewee_id', models.UUIDField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.survey')),
            ],
            options={
                'db_table': 'survey_sent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('interviewee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.interviewee')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.survey')),
            ],
            options={
                'db_table': 'survey_submissions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('end_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_item', to='api.item')),
                ('start_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_item', to='api.item')),
            ],
            options={
                'db_table': 'sections',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('value', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.item')),
            ],
            options={
                'db_table': 'questions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Precondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.option')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preconditions', to='api.item')),
                ('next_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='preconditions_next', to='api.item')),
            ],
            options={
                'db_table': 'preconditions',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='survey',
            field=models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, to='api.survey'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_numeric', models.IntegerField(blank=True, null=True)),
                ('content_character', models.TextField(blank=True, null=True)),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.submission')),
            ],
            options={
                'db_table': 'answers',
                'managed': True,
            },
        ),
    ]
