# Generated by Django 4.0.5 on 2022-06-27 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_question_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveysent',
            name='interviewee_id',
        ),
        migrations.AddField(
            model_name='creator',
            name='interviewees',
            field=models.ManyToManyField(to='api.interviewee'),
        ),
        migrations.AddField(
            model_name='surveysent',
            name='email',
            field=models.CharField(default='none@mail.com', editable=False, max_length=320),
        ),
        migrations.AlterField(
            model_name='item',
            name='survey',
            field=models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.survey'),
        ),
        migrations.AlterField(
            model_name='surveysent',
            name='id',
            field=models.CharField(editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
