# Generated by Django 4.0.5 on 2022-06-27 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_surveysent_interviewee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.survey'),
        ),
    ]
