# Generated by Django 4.0.5 on 2022-06-28 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_item_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='hash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.surveysent'),
        ),
        migrations.AlterField(
            model_name='surveysent',
            name='email',
            field=models.CharField(blank=True, editable=False, max_length=320, null=True),
        ),
    ]
